services:
  db:
    image: mongo:8.0
    container_name: vinom_db
    healthcheck:
      test: ["CMD", "mongosh", "-u", "${DB_USER}", "-p", "${DB_PASS}", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/data/db
    networks:
      - db_network

  app:
    build:
      context: . 
      dockerfile: Dockerfile
      target: prod-stage
    container_name: vinom_app
    ports:
      - "${REST_PORT}:${REST_PORT}"
    volumes:
      - .:/app
      - /app/tmp 
    environment:
      HOST_IP: app
      REST_PORT: ${REST_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      MATCHMAKING_HOST: ${MATCHMAKING_HOST}
      MATCHMAKING_PORT: ${MATCHMAKING_PORT}
      SESSION_PORT: ${SESSION_PORT}
      SESSION_HOST: ${SESSION_HOST}
      GIN_MODE: ${GIN_MODE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
    networks:
      - db_network 
    depends_on:
      db:
        condition: service_healthy

networks:
  db_network:
    driver: bridge

volumes:
  db_data:
    driver: local

